# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10ebc73d4836325e291bc2faec9c6cf727d2def1ef6ff29c178537f7cd917eac03486ade801cc0737fd71106d6e594353acdf62e59c68c026cf0f4a6a7ddd8ce

test:
  secret_key_base: 30def22b0252cc58f923ddb2d97b0b5fbbce83fc38728d31a22aa1eb864dc4e637bbaea2045467d1c0de194b6662215a48600fd02cdebf59cd8c3e7b6b52f563

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
